<Workspace Version="1.3.4.6666" X="97.2761908666268" Y="506.376169241761" zoom="1.42437388757074" ScaleFactor="1" Name="All Families Of Category" Description="Gets all famiies of a given category in the model  (does *not *work for system families)" ID="2a75c2fa-c410-434d-87af-f9d59ee44c4b" Category="Clockwork.Revit.Selection.ByCollector">
  <NamespaceResolutionMap>
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Category" resolvedName="Revit.Elements.Category" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="7051506d-0987-4906-8b5b-68f643bb6941" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-504.5279505166" y="-200.122408368294" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// Works with categories, BuiltInCategories and BuiltInCategories as strings&#xD;&#xA;category : var[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="27647f3a-c7d7-48fa-bf00-8adabac27375" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1340.4720494834" y="-126.122408368294" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="families" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="d32c6e00-b72b-406b-bb0d-ac9c12d5af51" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Element.ID+" x="598.4720494834" y="-200.122408368294" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <ID value="45153daa-f672-47f2-898f-f062bcb4e398" />
      <Name value="Element.ID+" />
      <Description value="Gets the ID of a given Revit elements. Unlike the OOTB Element.Id node, this node also works on mixed lists of Revit elements and categories." />
      <Inputs>
        <Input value="element" />
      </Inputs>
      <Outputs>
        <Output value="int" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="bb6e8fe3-86a6-4e99-94d4-7ae201a4ad89" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Category.FromInput" x="252.4720494834" y="-200.122408368294" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <ID value="3fe585a9-94df-4dce-99e1-306888ccb457" />
      <Name value="Category.FromInput" />
      <Description value="Returns a category from a category, a Dynamo-wrapped category, a BuiltInCategory or a string representing a BuiltInCategory." />
      <Inputs>
        <Input value="var[]..[]" />
      </Inputs>
      <Outputs>
        <Output value="RevitCategory" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <PythonNodeModels.PythonNode guid="b8ea796b-a5e7-41b4-874a-ef7b24218eca" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1116.4720494834" y="-126.122408368294" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import System
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

def FamiliesByCategoryId(catId, doc):
	collector = FilteredElementCollector(doc).OfClass(Family)
	return [x for x in collector.ToElements() if x.FamilyCategoryId.IntegerValue == catId]

inputdoc = UnwrapElement(IN[2])
if not inputdoc: doc = DocumentManager.Instance.CurrentDBDocument
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.RevitLinkInstance": doc = inputdoc.GetLinkDocument()
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.Document": doc = inputdoc
else: doc = DocumentManager.Instance.CurrentDBDocument

if isinstance(IN[0], list): OUT = [FamiliesByCategoryId(x, doc) for x in IN[0]]
else: OUT = FamiliesByCategoryId(IN[0], doc)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="86e66cba-645b-41a1-95de-0dd4a0c548c9" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="598.4720494834" y="-92.122408368294" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="toggle : bool = true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="5445afc6-1f3c-4d71-8248-25ab27252a13" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="598.4720494834" y="-8.122408368294" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// Use only if you want to query a linked model&#xD;&#xA;docOrRevitLinkInstance : var = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="7051506d-0987-4906-8b5b-68f643bb6941" start_index="0" end="bb6e8fe3-86a6-4e99-94d4-7ae201a4ad89" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d32c6e00-b72b-406b-bb0d-ac9c12d5af51" start_index="0" end="b8ea796b-a5e7-41b4-874a-ef7b24218eca" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bb6e8fe3-86a6-4e99-94d4-7ae201a4ad89" start_index="0" end="d32c6e00-b72b-406b-bb0d-ac9c12d5af51" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b8ea796b-a5e7-41b4-874a-ef7b24218eca" start_index="0" end="27647f3a-c7d7-48fa-bf00-8adabac27375" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="86e66cba-645b-41a1-95de-0dd4a0c548c9" start_index="0" end="b8ea796b-a5e7-41b4-874a-ef7b24218eca" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5445afc6-1f3c-4d71-8248-25ab27252a13" start_index="0" end="b8ea796b-a5e7-41b4-874a-ef7b24218eca" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>