<Workspace Version="1.3.4.6666" X="-15" Y="99" zoom="1" ScaleFactor="1" Name="Document.ComputeVolumes" Description="Returns whether or not the area and volume settings are set to compute volumes." ID="13f3b4fb-56da-4788-892f-b64fc4baec17" Category="Clockwork.Revit.Document.Query">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="1cbe60f1-372c-48b5-a73f-b2051756fa65" type="PythonNodeModels.PythonNode" nickname="Python Script" x="892.553072625699" y="192" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import Autodesk

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

inputdoc = UnwrapElement(IN[1])
if inputdoc == None:
	doc = DocumentManager.Instance.CurrentDBDocument
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.RevitLinkInstance":
	doc = inputdoc.GetLinkDocument()
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.Document":
	doc = inputdoc
else: doc = None

OUT = AreaVolumeSettings.GetAreaVolumeSettings(doc).ComputeVolumes</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="e11297bc-2917-4569-afdb-4f603e4b7451" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1116.5530726257" y="192" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="bool" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="65344c48-5ea8-48c1-820f-9419e188f5de" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="374.553072625699" y="163" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="toggle : bool = true;" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c74a5cb8-b84d-4e0a-ad15-d26e1f02a42b" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="374.553072625699" y="247" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// Use only if you want to query a linked model&#xD;&#xA;docOrRevitLinkInstance : var = null;" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="1cbe60f1-372c-48b5-a73f-b2051756fa65" start_index="0" end="e11297bc-2917-4569-afdb-4f603e4b7451" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="65344c48-5ea8-48c1-820f-9419e188f5de" start_index="0" end="1cbe60f1-372c-48b5-a73f-b2051756fa65" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c74a5cb8-b84d-4e0a-ad15-d26e1f02a42b" start_index="0" end="1cbe60f1-372c-48b5-a73f-b2051756fa65" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>